### ISSUE TITLE
missing 64-bit Android native libraries

### ISSUE THREAD

**Issue by martino2k6** [AdColony/AdColony-Unity-SDK-3#1]
Hi, I noticed that the Unity package is missing 64-bit ARM and x86 native libraries for Android when compared to the Android SDK. Would you please be able to let me know why they have been excluded? Thank you.

**Comment by cmanibog-ac** [comment]
The 64-bit ARM library was deliberately removed since Unity 5 only supports armeabi-v7a and x86 libraries. The x86 libraries should be included in the .unitypackage file. Could I have you check that this library is present when importing the package?

**Comment by martino2k6** [comment]
I was not aware of that Unity limitation, thanks. Yes, the x86 libraries are in the package.

**Comment by AntonyBlackett** [comment]
Unity now supports 64bit Arm. Can we get the 64 bit lib included please?
