### ISSUE TITLE
DEX error

### ISSUE THREAD

**Issue by JoRouss** [AdColony/AdColony-Unity-SDK-3#10]
Hi, I had DEX errors after importing AdColony (and google play services).

After some testing, I had to delete ADCDependencies, so I could delete the whole firebase folder under plugin.

I noticed some of the imported aar are version 9.0.1, everything from google play services is 10.0.1.

I did not import the PlayServicesResolver folder, since it's causing errors. Why does AdColony not use the same as everyone else? At least the same resolvers as GooglePlayServices and OneSignal. They are so easy to integrate.

Is this gonna cause any problems? Ads are still working.

**Comment by cmanibog-ac** [comment]
@JoRouss You should not see any issues with the older Google Play Services. We are using more recent versions in our demo apps for the native 3.0 Android SDK, with updates to our Unity plugin coming.

**Comment by JoRouss** [comment]
So you are saying I should wait for you to release a new version, compatible with the latest Google Play Services?

**Comment by JoRouss** [comment]
Can you tell me if the following manipulations will affect the ads revenue?

What I had to do to succesfully compile my game:

1. Import the unity package WITHOUT the PlayServicesResolver folder entirely.
2. Open the ADCDependencies.cs script. Change all 9.0.1 for 10.0.1. Change 23.4.0 for 24.0.0.
3. Delete ADCDependencies.cs && ADCMenu.cs && ADCSettingsWindow.cs
4. Delete firebase 9.0.1 plugin folder entirely.

So the question is, will this affect the ads revenue?

**Comment by smumair06** [comment]
Hi @JoRouss,
Your method works perfectly. I just want to confirm whether you faced any issue after deleting firebase folder. Like any sort of analytics missing on AdColony dashboard or any affect on earnings, something like that?

Thanks,

**Comment by JoRouss** [comment]
@smumair06 Everything seems to work fine.
