### ISSUE TITLE
Rewarded Video Ads Callback custom_id

### ISSUE THREAD

**Issue by CliffCawley** [AdColony/AdColony-Unity-SDK-3#11]
I can't figure out how to set the custom_id that your servers send to my server, it always comes out null.

I've tried the below:
```
var appOptions = new AdColony.AppOptions();
appOptions.UserId = "MyTestUser";
```

And then pass that to my AdColony.Ads.Configure but when the server sends the callback, custom_id is empty.

How should I be setting this id so that I can locate this user in my database?

**Comment by CliffCawley** [comment]
Ah, I had to find the correct documentation on the iOS SDK page here: https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Rewarded-Interstitial-Ads-Quick-Start-Guide

**Comment by cmanibog-ac** [comment]
Glad to hear you were able to find the correct documentation to sort this out. Thank you for the feedback and our Documentation team will look into updating our GitHub page.
