### ISSUE TITLE
AdColony.Ads.Configure doesn't callback

### ISSUE THREAD

**Issue by Dechichi01** [AdColony/AdColony-Unity-SDK-3#12]
Hey,

I have a Unity 5.4.3f1 project, with google play services integrated and now I'm trying to integrate AddColony, After going through the documentation setup, and also resolving the plugin conflict related in issue #10 (deleted firebase folder), the AdsConfigure function doesn't callback, and ads are never played.

I'm pretty sure the issue is related to deleting the firebase folder, since the sample project works fine. Still, in this case, anyone would have an idea on how to approach the problem related in issue #10 without deleting firebase-9.0.1 folder or just upgradind it maybe?

**Comment by cmanibog-ac** [comment]
@Dechichi01 The workaround proposed by JoRouss in #10 should still be a viable option. If this is not working for you, please submit a ticket to our support team at support@adcolony.com for further troubleshooting. In your message, please let us know what version of our Unity plugin you are using and if you are using a mediation layer, which partner. Please also send a device log from when our SDK is first initialized through this error.

**Comment by benjaminliutk** [comment]
I have the same issue, none of my callback was called, please help!
