### ISSUE TITLE
unable to import with google play games 0.9.36

### ISSUE THREAD

**Issue by htsoft** [AdColony/AdColony-Unity-SDK-3#13]
When in the project is already present Google Play Games plugin version 0.9.36, I'm unable to import AdColony unitypackage. There are conflicts about function redefinitions.
Unity3D version is 5.6.0f3

**Comment by cmanibog-ac** [comment]
Could you let me know what version of our Unity plugin you are using? I'm also checking with our Engineering team for additional insight on this. I'll follow up when I get more information on this.

**Comment by htsoft** [comment]
It's the 3.0.6 AdColony Plugin version

**Comment by cmanibog-ac** [comment]
We have updated the PlayServicesResolverin in our latest update. We have also removed some unneeded dependencies. Please update to v3.1.0 to resolve this. If there are any issues, feel free to reach out to our Support team directly by email at support@adcolony.com.
