### ISSUE TITLE
iOS: Returning to home screen mid-ad will mess up the screen orientation for portrait-only app

### ISSUE THREAD

**Issue by RickyJackson** [AdColony/AdColony-Unity-SDK-3#14]
Met this issue on iOS: When the app is set to portrait only, if you play a landscape ad and return to homescreen, the app orientation will be messed upon returning to the app.

**Comment by cmanibog-ac** [comment]
To look into this further, please send a full console log showing the app activity from when our SDK is initialized through this orientation issue. For streamlined communication, feel free to send this message to our support team directly by email at support@adcolony.com. I also recommend updating to our latest v3.1.0 plugin.

**Comment by kantagara** [comment]
Is this issue fixed?

**Comment by cmanibog-ac** [comment]
Orientation issues have been fixed in our 3.2+ SDK versions. Please update to our latest SDK version, v3.2.1, which can be downloaded at https://github.com/AdColony.
