### ISSUE TITLE
iOS: After video ready, if lose internet then play ad, ad will not show but have no callbacks to application

### ISSUE THREAD

**Issue by RickyJackson** [AdColony/AdColony-Unity-SDK-3#15]
Met this issue in iOS. Saw a log in xcode saying no internet connection, but no callbacks are triggered back in application

**Comment by cmanibog-ac** [comment]
Regarding checking for ad availability, I recommend reviewing our sample code at https://github.com/AdColony/AdColony-Unity-SDK-3/blob/master/ADCUnitySample/Assets/Scripts/GameController.cs. Once you request an ad with the zone id used in the configure call, you will get the callback AdColony.Ads.OnRequestInterstitialFailed or AdColony.Ads.OnRequestInterstitial. If an ad is not ready, you will receive the onRequestInterstitialFailed callback event. Here you may want to request an ad again. We also use AdColony.Ads.OnExpiring to check if the ad is expired. When an ad is available, you will receive the OnRequestInterstitial callback event, which is when an ad is available to show.
