### ISSUE TITLE
iOS app crashes if appID parameter on Ads.Configure is an empty string

### ISSUE THREAD

**Issue by MorganMoon** [AdColony/AdColony-Unity-SDK-3#16]
if you use an empty string and use Ads.Configure on iOS, the app will close out. Not a huge issue - but figured it should be known. I haven't tested if this is also the case on android aswell

**Comment by cmanibog-ac** [comment]
Could you provide a console log showing the app activity from when our SDK is initialized through this issue and a Charles log of the session. If you are using a mediation layer, which partner? For streamlined communication, feel free to send this as a message directly to our Support team by email at support@adcolony.com.
