### ISSUE TITLE
Receiving this error While building apk - Unable to convert classes into dex format

### ISSUE THREAD

**Issue by pandey623** [AdColony/AdColony-Unity-SDK-3#17]
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_111\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="System Users Path/AppData/Local/Android/Sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity_x_x_0\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorListenerCompat;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive H:\Unity Projects\AdMediation\Temp\StagingArea\android-libraries\AdColony\libs\.\AdColony.jar...
processing com/adcolony/adcolonysdk/BuildConfig.class...
processing com/adcolony/sdk/ADCDownload.class...
processing com/adcolony/sdk/ADCDownload$Listener.class...
processing com/adcolony/sdk/ADCNative.class...
processing com/adcolony/sdk/ADCVMModule.class...
processing com/adcolony/sdk/ADCVMModule$1.class...
processing com/adcolony/sdk/ADCVMModule$2.class...
processing com/adcolony/sdk/ADCVMModule$ADCJSVirtualMachine.class...
processing com/adcolony/sdk/ADCVMModule$ADCJSVirtualMachine$1.class...
processing com/adcolony/sdk/ADCVMModule$ADCJSVirtualMachine$a.class...
processing com/adcolony/sdk/AdColony.class...
processing com/adcolony/sdk/AdColony$1.class...
processing com/adcolony/sdk/AdColony$2.class...
processing com/adcolony/sdk/AdColony$3.class...
processing com/adcolony/sdk/AdColony$4.class...
processing com/adcolony/sdk/AdColony$5.class...
processing com/adcolony/sdk/AdColony$6.class...
processing com/adcolony/sdk/AdColony$7.class...
processing com/adcolony/sdk/AdColony$7$1.class...
processing com/adcolony/sdk/AdColony$8.class...
processing com/adcolony/sdk/AdColony$9.class...
processing com/adcolony/sdk/AdColonyAdOptions.class...
processing com/adcolony/sdk/AdColonyAdSize.class...
processing com/adcolony/sdk/AdColonyAdViewActivity.class...
processing com/adcolony/sdk/AdColonyAppOptions.class...
processing com/adcolony/sdk/AdColonyCustomMessage.class...
processing com/adcolony/sdk/AdColonyCustomMessage$1.class...
processing com/adcolony/sdk/AdColonyCustomMessageListener.class...
processing com/adcolony/sdk/AdColonyInterstitial.class...
processing com/adcolony/sdk/AdColonyInterstitialActivity.class...
processing com/adcolony/sdk/AdColonyInterstitialListener.class...
processing com/adcolony/sdk/AdColonyNativeAdView.class...
processing com/adcolony/sdk/AdColonyNativeAdView$1.class...
processing com/adcolony/sdk/AdColonyNativeAdView$EngagementButton.class...
processing com/adcolony/sdk/AdColonyNativeAdViewListener.class...
processing com/adcolony/sdk/AdColonyPubServices.class...
processing com/adcolony/sdk/AdColonyPubServices$LogLevel.class...
processing com/adcolony/sdk/AdColonyPubServices$NotificationType.class...
processing com/adcolony/sdk/AdColonyPubServices$ServiceAvailability.class...
processing com/adcolony/sdk/AdColonyPubServicesCallbacks.class...
processing com/adcolony/sdk/AdColonyPubServicesConReceiver.class...
processing com/adcolony/sdk/AdColonyPubServicesConReceiver$1.class...
processing com/adcolony/sdk/AdColonyPubServicesConReceiver$2.class...
processing com/adcolony/sdk/AdColonyPubServicesConReceiver$3.class...
processing com/adcolony/sdk/AdColonyPubServicesDigitalItem.class...
processing com/adcolony/sdk/AdColonyPubServicesInAppMsgActivity.class...
processing com/adcolony/sdk/AdColonyPubServicesInAppMsgActivity$1.class...
processing com/adcolony/sdk/AdColonyPubServicesInAppMsgActivity$2.class...
processing com/adcolony/sdk/AdColonyPubServicesOverlayActivity.class...
processing com/adcolony/sdk/AdColonyPubServicesPushGcmListenerService.class...
processing com/adcolony/sdk/AdColonyPubServicesPushNotification.class...
processing com/adcolony/sdk/AdColonyPubServicesPushRegIdIntentService.class...
processing com/adcolony/sdk/AdColonyPubServicesPushRegIdListenerService.class...
processing com/adcolony/sdk/AdColonyPubServicesVIPInformation.class...
processing com/adcolony/sdk/AdColonyReward.class...
processing com/adcolony/sdk/AdColonyRewardListener.class...
processing com/adcolony/sdk/AdColonyUserMetadata.class...
processing com/adcolony/sdk/AdColonyZone.class...
processing com/adcolony/sdk/MessagingLaunchActivity.class...
processing com/adcolony/sdk/OverlayActivityImpl.class...
processing com/adcolony/sdk/YvolverDeepLinkManager.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$1.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$1$1.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$2.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$3.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$3$1.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$4.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$5.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$DeepLink.class...
processing com/adcolony/sdk/YvolverDeepLinkManager$DeepLinkBridge.class...
processing com/adcolony/sdk/a.class...
processing com/adcolony/sdk/a$1.class...
processing com/adcolony/sdk/aa.class...
processing com/adcolony/sdk/aa$a.class...
processing com/adcolony/sdk/aa$b.class...
processing com/adcolony/sdk/aa$c.class...
processing com/adcolony/sdk/aa$d.class...
processing com/adcolony/sdk/aa$e.class...
processing com/adcolony/sdk/aa$f.class...
processing com/adcolony/sdk/aa$g.class...
processing com/adcolony/sdk/aa$h.class...
processing com/adcolony/sdk/aa$i.class...
processing com/adcolony/sdk/aa$j.class...
processing com/adcolony/sdk/aa$k.class...
processing com/adcolony/sdk/aa$l.class...
processing com/adcolony/sdk/aa$m.class...
processing com/adcolony/sdk/aa$n.class...
processing com/adcolony/sdk/aa$o.class...
processing com/adcolony/sdk/aa$p.class...
processing com/adcolony/sdk/aa$q.class...
processing com/adcolony/sdk/aa$r.class...
processing com/adcolony/sdk/aa$s.class...
processing com/adcolony/sdk/aa$t.class...
processing com/adcolony/sdk/ab.class...
processing com/adcolony/sdk/ab$1.class...
processing com/adcolony/sdk/ab$2.class...
processing com/adcolony/sdk/ac.class...
processing com/adcolony/sdk/ad.class...
processing com/adcolony/sdk/ae.class...
processing com/adcolony/sdk/af.class...
processing com/adcolony/sdk/ag.class...
processing com/adcolony/sdk/ag$1.class...
processing com/adcolony/sdk/ah.class...
processing com/adcolony/sdk/ai.class...
processing com/adcolony/sdk/ai$a.class...
processing com/adcolony/sdk/aj.class...
processing com/adcolony/sdk/aj$1.class...
processing com/adcolony/sdk/ak.class...
processing com/adcolony/sdk/ak$a.class...
processing com/adcolony/sdk/ak$b.class...
processing com/adcolony/sdk/ak$c.class...
processing com/adcolony/sdk/ak$d.class...
processing com/adcolony/sdk/ak$e.class...
processing com/adcolony/sdk/ak$f.class...
processing com/adcolony/sdk/al.class...
processing com/adcolony/sdk/al$1.class...
processing com/adcolony/sdk/am.class...
processing com/adcolony/sdk/an.class...
processing com/adcolony/sdk/ao.class...
processing com/adcolony/sdk/ao$1.class...
processing com/adcolony/sdk/ao$10.class...
processing com/adcolony/sdk/ao$11.class...
processing com/adcolony/sdk/ao$12.class...
processing com/adcolony/sdk/ao$13.class...
processing com/adcolony/sdk/ao$14.class...
processing com/adcolony/sdk/ao$15.class...
processing com/adcolony/sdk/ao$2.class...
processing com/adcolony/sdk/ao$3.class...
processing com/adcolony/sdk/ao$4.class...
processing com/adcolony/sdk/ao$5.class...
processing com/adcolony/sdk/ao$6.class...
processing com/adcolony/sdk/ao$7.class...
processing com/adcolony/sdk/ao$8.class...
processing com/adcolony/sdk/ao$9.class...
processing com/adcolony/sdk/ap.class...
processing com/adcolony/sdk/aq.class...
processing com/adcolony/sdk/ar.class...
processing com/adcolony/sdk/as.class...
processing com/adcolony/sdk/as$1.class...
processing com/adcolony/sdk/as$10.class...
processing com/adcolony/sdk/as$2.class...
processing com/adcolony/sdk/as$3.class...
processing com/adcolony/sdk/as$4.class...
processing com/adcolony/sdk/as$5.class...
processing com/adcolony/sdk/as$6.class...
processing com/adcolony/sdk/as$7.class...
processing com/adcolony/sdk/as$8.class...
processing com/adcolony/sdk/as$9.class...
processing com/adcolony/sdk/at.class...
processing com/adcolony/sdk/au.class...
processing com/adcolony/sdk/au$a.class...
processing com/adcolony/sdk/au$b.class...
processing com/adcolony/sdk/av.class...
processing com/adcolony/sdk/av$1.class...
processing com/adcolony/sdk/av$2.class...
processing com/adcolony/sdk/av$3.class...
processing com/adcolony/sdk/av$4.class...
processing com/adcolony/sdk/av$5.class...
processing com/adcolony/sdk/av$6.class...
processing com/adcolony/sdk/av$7.class...
processing com/adcolony/sdk/av$7$1.class...
processing com/adcolony/sdk/av$a.class...
processing com/adcolony/sdk/aw.class...
processing com/adcolony/sdk/aw$1.class...
processing com/adcolony/sdk/aw$2.class...
processing com/adcolony/sdk/aw$3.class...
processing com/adcolony/sdk/aw$4.class...
processing com/adcolony/sdk/aw$5.class...
processing com/adcolony/sdk/aw$6.class...
processing com/adcolony/sdk/aw$7.class...
processing com/adcolony/sdk/aw$8.class...
processing com/adcolony/sdk/aw$a.class...
processing com/adcolony/sdk/ax.class...
processing com/adcolony/sdk/ax$1.class...
processing com/adcolony/sdk/ay.class...
processing com/adcolony/sdk/az.class...
processing com/adcolony/sdk/b.class...
processing com/adcolony/sdk/b$1.class...
processing com/adcolony/sdk/ba.class...
processing com/adcolony/sdk/bb.class...
processing com/adcolony/sdk/bc.class...
processing com/adcolony/sdk/bd.class...
processing com/adcolony/sdk/be.class...
processing com/adcolony/sdk/be$1.class...
processing com/adcolony/sdk/be$2.class...
processing com/adcolony/sdk/be$3.class...
processing com/adcolony/sdk/be$4.class...
processing com/adcolony/sdk/be$5.class...
processing com/adcolony/sdk/be$a.class...
processing com/adcolony/sdk/bf.class...
processing com/adcolony/sdk/bf$1.class...
processing com/adcolony/sdk/bf$10.class...
processing com/adcolony/sdk/bf$11.class...
processing com/adcolony/sdk/bf$2.class...
processing com/adcolony/sdk/bf$3.class...
processing com/adcolony/sdk/bf$4.class...
processing com/adcolony/sdk/bf$5.class...
processing com/adcolony/sdk/bf$6.class...
processing com/adcolony/sdk/bf$7.class...
processing com/adcolony/sdk/bf$8.class...
processing com/adcolony/sdk/bf$9.class...
processing com/adcolony/sdk/bg.class...
processing com/adcolony/sdk/bg$1.class...
processing com/adcolony/sdk/bg$10.class...
processing com/adcolony/sdk/bg$10$1.class...
processing com/adcolony/sdk/bg$1$1.class...
processing com/adcolony/sdk/bg$11.class...
processing com/adcolony/sdk/bg$12.class...
processing com/adcolony/sdk/bg$13.class...
processing com/adcolony/sdk/bg$14.class...
processing com/adcolony/sdk/bg$15.class...
processing com/adcolony/sdk/bg$16.class...
processing com/adcolony/sdk/bg$17.class...
processing com/adcolony/sdk/bg$18.class...
processing com/adcolony/sdk/bg$19.class...
processing com/adcolony/sdk/bg$2.class...
processing com/adcolony/sdk/bg$20.class...
processing com/adcolony/sdk/bg$21.class...
processing com/adcolony/sdk/bg$22.class...
processing com/adcolony/sdk/bg$23.class...
processing com/adcolony/sdk/bg$23$1.class...
processing com/adcolony/sdk/bg$24.class...
processing com/adcolony/sdk/bg$25.class...
processing com/adcolony/sdk/bg$26.class...
processing com/adcolony/sdk/bg$27.class...
processing com/adcolony/sdk/bg$28.class...
processing com/adcolony/sdk/bg$29.class...
processing com/adcolony/sdk/bg$29$1.class...
processing com/adcolony/sdk/bg$3.class...
processing com/adcolony/sdk/bg$30.class...
processing com/adcolony/sdk/bg$31.class...
processing com/adcolony/sdk/bg$32.class...
processing com/adcolony/sdk/bg$33.class...
processing com/adcolony/sdk/bg$34.class...
processing com/adcolony/sdk/bg$4.class...
processing com/adcolony/sdk/bg$5.class...
processing com/adcolony/sdk/bg$6.class...
processing com/adcolony/sdk/bg$7.class...
processing com/adcolony/sdk/bg$7$1.class...
processing com/adcolony/sdk/bg$8.class...
processing com/adcolony/sdk/bg$8$1.class...
processing com/adcolony/sdk/bg$8$2.class...
processing com/adcolony/sdk/bg$9.class...
processing com/adcolony/sdk/bg$a.class...
processing com/adcolony/sdk/bh.class...
processing com/adcolony/sdk/bh$1.class...
processing com/adcolony/sdk/bh$10.class...
processing com/adcolony/sdk/bh$2.class...
processing com/adcolony/sdk/bh$3.class...
processing com/adcolony/sdk/bh$4.class...
processing com/adcolony/sdk/bh$5.class...
processing com/adcolony/sdk/bh$6.class...
processing com/adcolony/sdk/bh$7.class...
processing com/adcolony/sdk/bh$8.class...
processing com/adcolony/sdk/bh$9.class...
processing com/adcolony/sdk/bi.class...
processing com/adcolony/sdk/bi$1.class...
processing com/adcolony/sdk/bi$2.class...
processing com/adcolony/sdk/bi$2$1.class...
processing com/adcolony/sdk/bi$3.class...
processing com/adcolony/sdk/bi$3$1.class...
processing com/adcolony/sdk/bi$3$2.class...
processing com/adcolony/sdk/bi$4.class...
processing com/adcolony/sdk/bi$5.class...
processing com/adcolony/sdk/bi$6.class...
processing com/adcolony/sdk/bi$7.class...
processing com/adcolony/sdk/bi$8.class...
processing com/adcolony/sdk/bi$a.class...
processing com/adcolony/sdk/bi$b.class...
processing com/adcolony/sdk/bi$c.class...
processing com/adcolony/sdk/bi$d.class...
processing com/adcolony/sdk/bi$e.class...
processing com/adcolony/sdk/bi$f.class...
processing com/adcolony/sdk/bi$g.class...
processing com/adcolony/sdk/bi$g$1.class...
processing com/adcolony/sdk/bj.class...
processing com/adcolony/sdk/bj$1.class...
processing com/adcolony/sdk/bj$2.class...
processing com/adcolony/sdk/bj$3.class...
processing com/adcolony/sdk/bk.class...
processing com/adcolony/sdk/bl.class...
processing com/adcolony/sdk/bm.class...
processing com/adcolony/sdk/bn.class...
processing com/adcolony/sdk/bn$a.class...
processing com/adcolony/sdk/bn$b.class...
processing com/adcolony/sdk/bo.class...
processing com/adcolony/sdk/bp.class...
processing com/adcolony/sdk/bq.class...
processing com/adcolony/sdk/br.class...
processing com/adco<message truncated>

**Comment by cmanibog-ac** [comment]
What version of our Unity plugin are you integrating with? If you have not already done so, I recommend updating to our latest 3.1 plugin. If this issue still occurs after updating, please submit a ticket to our support team at support@adcolony.com.

**Comment by CliffCawley** [comment]
Most likely you have multiple versions of the same .aar in your Plugins/Android directory. 

i.e. play-services-ads-9.8.0.aar and play-services-ads-10.1.0.aar

Since AdColony uses the google play resolved, you can delete (make sure you backup!) all of the google services .aar files and then let it regenerate them. That way it will only add one version and you won't be left with leftovers.
