### ISSUE TITLE
Failing to build in Unity Cloud Build. 

### ISSUE THREAD

**Issue by madawe** [AdColony/AdColony-Unity-SDK-3#18]
Using the newest release.

It builds fine locally but on Unity Cloud Build I get this error:

34888: [Unity] -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp-Editor.dll
34889: [Unity] Compilation failed: 1 error(s), 0 warnings
34890: [Unity] Assets/AdColony/Editor/ADCPostBuildProcessor.cs(17,13): error CS0103: The name `ProcessPostBuild' does not exist in the current context
34891: [Unity] - Finished compile Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
34892: [Unity] Assets/AdColony/Editor/ADCPostBuildProcessor.cs(17,13): error CS0103: The name `ProcessPostBuild' does not exist in the current context
34893: [Unity] (Filename: Assets/AdColony/Editor/ADCPostBuildProcessor.cs Line: 17)
34894: [Unity] Validating Project structure ... 0.070363 seconds.
34895: [Unity] Refresh: detecting if any assets need to be imported or removed ... Refresh: elapses 0.067976 seconds (Nothing changed)

**Comment by CliffCawley** [comment]
I've got the same issue :(

**Comment by cmanibog-ac** [comment]
Our Unity plugin is built for compatibility with Unity 3D Engine and other developers have run into this issue when building in Unity Cloud Build. I recommend reaching out to the Unity Cloud team and development forums for additional guidance on this type of setup. Is it critical that Cloud Build be used instead of Unity 3d or would you and your team be able to make this switch? Support for Unity Cloud Build is not currently on our development roadmap.

**Comment by CliffCawley** [comment]
You're explicitly checking for Cloud Build in `ADCPostBuildProcessor.cs` with the following:

```
namespace AdColony.Editor {
    public class ADCPostBuildProcessor : MonoBehaviour {

#if UNITY_CLOUD_BUILD
        public static void OnPostprocessBuildiOS(string exportPath) {
            ProcessPostBuild(BuildTarget.iOS, exportPath);
        }
#endif

```

So it looks like you support Cloud Build, however we're saying it's not currently working.

**Comment by cmanibog-ac** [comment]
Our team is currently looking into this and working towards a solution. We'll follow up with more information after this investigation.

**Comment by ckadominguez** [comment]
Same happening hear. I hope you can provide a solution soon. Thanks!

**Comment by shawnkc** [comment]
It appears that replacing the corresponding ADCPostBuildProcessor code with this snippet works:

#if UNITY_CLOUD_BUILD
        public static void OnPostprocessBuildiOS(string exportPath) {
            OnPostprocessBuild(BuildTarget.iOS, exportPath);
        }
#endif

        [PostProcessBuildAttribute(1)]
        public static void OnPostprocessBuild(BuildTarget buildTarget, string buildPath) {
            if (buildTarget == BuildTarget.iOS) {
#if UNITY_IOS
                Debug.Log("AdColony: OnPostprocessBuild");
                UpdateProject(buildTarget, buildPath + "/Unity-iPhone.xcodeproj/project.pbxproj");
                UpdateProjectPlist(buildTarget, buildPath + "/Info.plist");
#endif
            }
        }
