### ISSUE TITLE
ADCSettingsWindow.cs Compile error on Android

### ISSUE THREAD

**Issue by CliffCawley** [AdColony/AdColony-Unity-SDK-3#19]
ADCSettingsWindow.cs
```
                    ADCManifestProcessor.Process();
#if UNITY_ANDROID
                    ADCDependencies.ResetDependencies();
#endif
                    AssetDatabase.Refresh();
```

`ADCDependencies.ResetDependencies();` can no longer be found.

Looks like `ADCDependencies.cs` has been updated and now the class is called `SampleDependencies`. Which I think is incorrect anyway, because that's the google resolver demo name.

The original Reset method no longer exists, but used to contain:
```
        public static void ResetDependencies() {
			Google.VersionHandler.InvokeInstanceMethod(
			svcSupport, "ClearDependencies", null);
            RegisterDependencies();
        }
```

Question is, is that still needed? If so, it'll need to be added back and that SampleDependencies class should also be renamed to match the filename as usually Unity complains about that.

**Comment by cmanibog-ac** [comment]
Our team will review this further. I will follow up once I receive more information.

**Comment by shawnkc** [comment]
This is the same fix as https://github.com/AdColony/AdColony-Unity-SDK-3/issues/20#issuecomment-300335912.

It will be fixed in the next version, but if you want to get past the issue right now, you can rename both SampleDependencies references to ADCDependencies within ADCDependencies.cs. There were other changes from the Google sample within the file but those two references were an oversight.

**Comment by CliffCawley** [comment]
Thanks for the update, should the fix include the `ResetDependencies` old code, or has that been removed completely?

Would it be possible for you to version the source and create the package as a release so we can see the diffs and any current work?

**Comment by shawnkc** [comment]
We're considering open sourcing all of our source and allowing contributions. But for now, here are the only significant changes for your issues:
<img width="1243" alt="screen shot 2017-05-16 at 8 36 23 am" src="https://cloud.githubusercontent.com/assets/1760855/26108902/74ceccf0-3a13-11e7-85b9-5e013f1b23ef.png">
<img width="1240" alt="screen shot 2017-05-16 at 8 36 48 am" src="https://cloud.githubusercontent.com/assets/1760855/26108904/75401b4e-3a13-11e7-89f1-4e16d9e4c1a8.png">

**Comment by CliffCawley** [comment]
Sounds good, thanks! :)
