### ISSUE TITLE
Make an Android or iOS version only?

### ISSUE THREAD

**Issue by Warface** [AdColony/AdColony-Unity-SDK-3#2]
Since I don't build for iOS yet. I've not installed the iOS SDK for Unity and the new AdColony SDK3 is not working properly and have errors in the compilation like

The name 'PBXProject' does not exist in the current context	zombie run.CSharp.Editor	..\Assets\AdColony\Editor\ADCPostBuildProcessor.cs

The past SDK was working find, can I still use the old one? Where is it now that the Git is updated with the new one.

Thanks

**Comment by cmanibog-ac** [comment]
Our 2.x Unity plugin can still be downloaded at https://github.com/AdColony/AdColony-Unity-SDK.
