### ISSUE TITLE
ADCDependencies.cs is just the google Resolver sample

### ISSUE THREAD

**Issue by CliffCawley** [AdColony/AdColony-Unity-SDK-3#20]
In the previous revision, this file used to have the actual dependencies for AdColony.

The new version seems to be just a copy of the Google Sample, including the name of the demo sample class.

**Comment by cmanibog-ac** [comment]
Our team will look into this further. We will follow up after reviewing.

**Comment by shawnkc** [comment]
This new version of the SDK has less dependencies than previous versions of the SDK. The name of the class was an oversight in this release and is targeted for a hotfix. You can rename both SampleDependencies references to in ADCDependencies.cs to ADCDependencies to have what the changes will be in the hotfix. We did have some changes in the file from the example.
