### ISSUE TITLE
Typo in Video Ad Quick Start Guide Wiki

### ISSUE THREAD

**Issue by timendez** [AdColony/AdColony-Unity-SDK-3#22]
https://github.com/AdColony/AdColony-Unity-SDK-3/wiki/Showing-Video-Ads-Quick-Start-Guide

Under Showing a Video Ad...

```
void PlayAd() {
    if (Ad != null) {
        AdColony.Ads.ShowAd(_ad);
    }
}
```

`Ad` -> `_ad`

**Comment by cmanibog-ac** [comment]
Thank you for the feedback. I've reached out to our team managing our Wiki to manage this.

**Comment by Warface** [comment]
So it should be like this?

```
void PlayAd() {
    if (_ad != null) {
        AdColony.Ads.ShowAd(_ad);
    }
}
```

or the example above was already correct?

**Comment by shawnkc** [comment]
Yes, you're correct. We'll fix this ASAP.

**Comment by shawnkc** [comment]
Yeah, we can do that. However, the examples were only intended to be psuedo-code.

OnRequestInterstitial already uses _ad. Am I missing something?

**Comment by Warface** [comment]
Yeah now it is since you've just updated the doc ;)

Earlier it was

`Ad = ad`

Anyway the doc is now more accurate 

Thank you

**Comment by shawnkc** [comment]
Ok, cool. Thanks for your comments.
