### ISSUE TITLE
iOS plist modifications (XCode 8.x+)

### ISSUE THREAD

**Issue by JSC-Sparkling** [AdColony/AdColony-Unity-SDK-3#23]
When building for iOS using XCode 8.x+ there are no plist modifications made while they actually are 
required according to your own native iOS plugin's documentation/readme (found here: https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Xcode-Project-Setup#configuring-privacy-controls) in order to be able to submit the app.

**Comment by shawnkc** [comment]
Thanks for your comment! We have fixed this and will have it within our 3.2 release this month. Let me know if you'd like an interim fix.
