### ISSUE TITLE
Application Dont Pause on iOS

### ISSUE THREAD

**Issue by Cruz182** [AdColony/AdColony-Unity-SDK-3#25]
While a video is showed, the application dont pause.

**Comment by cmanibog-ac** [comment]
@Cruz182 - To look into this further, please share a full console log showing the app activity from when our SDK is initialized through this issue. Are you using our latest 3.1.0 Unity plugin? If a mediation layer is being used, which partner?

Could I have you check that our integration documentation has been followed at https://github.com/AdColony/AdColony-Unity-SDK-3#installation? Please also review our sample app for further discussion and integration guidance at https://github.com/AdColony/AdColony-Unity-SDK-3/blob/7dac1bbd179ac8e1083ec198acc443cf0d1a9b91/ADCUnitySample/Assets/Scripts/GameController.cs.

For streamlined communication with our Support/Engineering team, feel free to send this information as a ticket to support@adcolony.com.
