### ISSUE TITLE
ERROR_BROKEN_PIPE error in Unity when building sample

### ISSUE THREAD

**Issue by MeltdownZA** [AdColony/AdColony-Unity-SDK-3#27]
I opened your sample project in Unity 5.6.3p1 and imported the latest Unity Package for your SDK.

When I try to build for Android I get the following error...

IOException: Win32 IO returned ERROR_BROKEN_PIPE. Path: D:\AdColony-Unity-SDK-3-master\AdColony-Unity-SDK-3-master\ADCUnitySample\[Unknown]
System.IO.FileStream.FlushBuffer (System.IO.Stream st) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:1040)
System.IO.FileStream.FlushBuffer () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:1054)
System.IO.FileStream.Flush () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:859)
System.IO.StreamWriter.Flush () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/StreamWriter.cs:191)
System.IO.StreamWriter.Dispose (Boolean disposing) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/StreamWriter.cs:162)
UnityEditor.HostView:OnGUI()

I also tried to update the manifest using the menu dropdown option, but it didn't help.

Any ideas?

**Comment by shawnkc** [comment]
I am looking into the issue.

**Comment by shawnkc** [comment]
Sorry it took so long to respond, but we were unable to reproduce this issue. Did you ever get past it?
