### ISSUE TITLE
Issue exporting AndroidStudio project

### ISSUE THREAD

**Issue by FedericoLaGreca** [AdColony/AdColony-Unity-SDK-3#28]
Hello,

we currently build our Unity app by exporting an AndroidStudio project and building from there. If we do so, we get this error when building:

```
Error:Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/adcolony/unityplugin/BuildConfig;
```

We currently solved it by including the two *.jar libraries (AdColony and AdColonyUnityWrapper) as pure jars and manually adding the required manifest entries, instead of letting AdColony create an AndroidStudio module.

Any clues on what might be causing this issue, or more info you might need?

**Comment by shawnkc** [comment]
Are you using this latest 3.2.1 version? Also, did you completely remove the older version?

**Comment by FedericoLaGreca** [comment]
We are using 3.2.1 and this was our first integration with AdColony

**Comment by shawnkc** [comment]
What version of Unity are you using?

**Comment by shawnkc** [comment]
Are you exporting via Gradle or Legacy? Does it build properly from within Unity without exporting the project?

**Comment by brisa0730** [comment]
Having the same issue. I am using Gradle build.
(Google Resolver is killing me with all that dex limitation errors. I have no choice but to use Gradle)

I tried with a new clean project and imported AdColony 3.2.1 only, no other assets. 
Still showing the same error.

**Comment by FedericoLaGreca** [comment]
Sorry for the late response. We are exporting with Gradle and unity 5.6.2p2

**Comment by shawnkc** [comment]
We have a fix for it that is in final testing. Changing the package name in AndroidManifestTemplate.xml to something other than "com.adcolony.unityplugin" should solve the problem.

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.adcolony.unitypluginpackage">`
