### ISSUE TITLE
There's no event for when user fail to show an ad (with no Internet)

### ISSUE THREAD

**Issue by Whyser** [AdColony/AdColony-Unity-SDK-3#29]
To replicate on both Android and iOS:
1. Start app with Internet access
2. Disable Internet access
3. Open app again (from memory, NOT from a complete re-boot)
4. Ad will be available since it was still "cached"
5. Ad will not show.
6. Ad Colony will print out in the console "No internet connection, blabla"

There is NO WAY of getting this information callback-wise, which causes weird states in the application. Give us a callback OnAdFailToShow or something similar.

**Comment by cmanibog-ac** [comment]
When an ad attempts to play with no network connection, then it runs into the network issue and logs the error that you are seeing. 

A workaround for this is to check for network reachability before invoking AdColony; we are using SCNetworkReachabilityStatus to determine network settings. This will resolve this issue as even if the video is available, but there is no network, the app will not make an attempt to play the ad.

**Comment by cmanibog-ac** [comment]
Thanks for bringing this to our attention. Our team has taken this into account and added this to our development roadmap for a more direct solution.
