### ISSUE TITLE
Wiki edit

### ISSUE THREAD

**Issue by Warface** [AdColony/AdColony-Unity-SDK-3#3]
In your new documentation, you should edit this page for the "Request a Video Ad"

https://github.com/AdColony/AdColony-Unity-SDK-3/wiki/Showing-Video-Ads-Quick-Start-Guide

On the line

`AdColony.Ads.RequestInterstitialAd(Constants.CurrencyZoneID, adOptions);`

please change it to

`AdColony.Ads.RequestInterstitialAd( /* Zone Id */ , adOptions);`

the doc should not refer to a sample in the git but based on a blank project. Been searching for a while on where that "Constants" var was at.

Thanks

**Comment by superjd** [comment]
Thanks for reporting this, we have updated the documentation.
