### ISSUE TITLE
None of my callback was called

### ISSUE THREAD

**Issue by benjaminliutk** [AdColony/AdColony-Unity-SDK-3#31]
Unity version 2017.2, adcolony version 3.2.1.

		AdColony.Ads.OnConfigurationCompleted += (List<AdColony.Zone> zones_) => {
			Debug.Log("AdColony.Ads.OnConfigurationCompleted called");

			if (zones_ == null || zones_.Count <= 0) {
				Debug.Log("adcolony config failed");
			}
			else {
				Debug.Log("adcolony config success");
			}
		};
AdColony.Ads.Configure(AdsConfig.AdColonyAppID, appOptions, zoneIds);
I called like above, callback was not called, and log only shows:
01-05 17:26:50.870 13250-13279/cn.playinfinity.game.wordsdom2 E/AdColony: JNI_OnLoad
01-05 17:26:50.880 13250-13279/cn.playinfinity.game.wordsdom2 I/AdColony [INFO]: Configuring AdColony
01-05 17:35:21.378 21837-21867/cn.playinfinity.game.wordsdom2 I/System.out: [vz58b469b990784736aa, vz18ad1f670e964cf0a5]

Is there any way to see more logs like open verbose or debug logs please?

**Comment by shawnkc** [comment]
Can you confirm you are seeing this on an Android device?

**Comment by shawnkc** [comment]
Are you able to show ads even though you don't receive a callback notification? 
Is it possible that this `OnConfigurationCompleted` event is subscribed to after `configure()` is called?
