### ISSUE TITLE
InterstitialAd not Expiring.

### ISSUE THREAD

**Issue by Aakashh94DP** [AdColony/AdColony-Unity-SDK-3#32]
According to the comments in the InterstitialAd.cs class, the Expired property in an InterstitialAd should be set to true as soon as an Ad is opened.

![image](https://user-images.githubusercontent.com/20633295/33256862-e3555918-d38e-11e7-9ed3-9c451395555d.png)

The problem is that when I play call my **ShowInterstitial()** method for the first time, the ad plays, but the "adColonyInterstitialNormalAd" variable is not set to expired, thus the **Ads_OnExpiring** event in my class is not triggered and a new Ad isnt requested. 

So if I try to call the **ShowInterstitial()** method again, my **HasAd()** print that the Ad is not expired and returns true, so then the code will try to play the ad and the following will show in the logs in XCode.

"AdColony [*** ERROR ***] : Tried to show an expired interstitial ad."

Im using plugin version 3.2.1

```
using System.Collections.Generic;
using UnityEngine;
using AdColony;

public class AdColonyTest : MonoBehaviour
{
    private InterstitialAd adColonyInterstitialNormalAd = null;
    private InterstitialAd adColonyInterstitialRewardAd = null;

    //Hidden ids for demonstration
    private string iosAppID = "replace_this_with_your_app_id";
    private string normalAdZoneID = "replace_this_with_your_zone_id";

    private void Awake()
    {
        SetUpAdColony();
    }

    public void ShowInterstitial()
    {
        bool hasAd = HasAd();

        if (hasAd)
        {
            Ads.ShowAd(this.adColonyInterstitialNormalAd);
        }
        else
        {
            RequestNormalInterstitialAd();
        }
    }

    private bool HasAd()
    {
        Debug.Log("Has normal ad " + !this.adColonyInterstitialNormalAd.Expired);
        return this.adColonyInterstitialNormalAd != null && !this.adColonyInterstitialNormalAd.Expired;
    }

    private void SetUpAdColony()
    {
        Ads.OnConfigurationCompleted += Ads_OnConfigurationCompleted;
        Ads.OnRequestInterstitial += Ads_OnRequestInterstitial;
        Ads.OnExpiring += Ads_OnExpiring;
        Ads.OnOpened += Ads_OnOpened;
        Ads.OnClosed += Ads_OnClosed;

        ConfigureAdColony();
    }

    private void ConfigureAdColony()
    {
        AppOptions options = new AppOptions();
        options.AdOrientation = AdOrientationType.AdColonyOrientationPortrait;

        string[] zoneIds = new string[] { normalAdZoneID };

        Ads.Configure(iosAppID, options, zoneIds);
    }

    private void RequestNormalInterstitialAd()
    {
        Ads.RequestInterstitialAd(normalAdZoneID, null);
    }

    private void Ads_OnConfigurationCompleted(List<Zone> obj)
    {
        RequestNormalInterstitialAd();
    }

    private void Ads_OnOpened(InterstitialAd ad)
    {
        Debug.Log("Ad opened");
    }

    private void Ads_OnClosed(InterstitialAd ad)
    {
        Debug.Log("Ad closed");
    }

    private void Ads_OnExpiring(InterstitialAd ad)
    {
        if (ad == adColonyInterstitialNormalAd)
        {
            RequestNormalInterstitialAd();
        }
    }

    private void Ads_OnRequestInterstitial(InterstitialAd ad)
    {
        if (ad.ZoneId == normalAdZoneID)
        {
            this.adColonyInterstitialNormalAd = ad;
        }
    }
}
```

**Comment by shawnkc** [comment]
Thank you for contacting us with your very clearly explained issue and example code. We are investigating the issue.

**Comment by shawnkc** [comment]
Are you seeing this on Android, iOS devices, or both?

**Comment by Aakashh94DP** [comment]
@shawnkc Currently I am only testing with IOS. No plans for Android at the moment

**Comment by shawnkc** [comment]
There are a few issues at work here:
1. There is a bug in the expired flag coming back to the OnClosed callback. Until 3.3 is released, you can set work around that issue by setting the expired flag yourself within the OnClosed callback.
2. IntestitialAd objects that are returned to the callbacks are new objects, so after it's shown, using the same object isn't valid. Checking the zone like you were doing for the request callback is a better way to handle it. 
3. We have made it more clear in the upcoming documentation how the OnExpiring callback works. This is only called when the ad naturally expires, not when it expires due to it being shown. We are considering consolidating this so requests only need to be made in one callback.

private void Ads_OnClosed(InterstitialAd ad)
{
    if (ad.ZoneId == normalAdZoneID)
    {
        RequestNormalInterstitialAd();
    }
}

private void Ads_OnExpiring(InterstitialAd ad)
{
    if (ad.ZoneId == normalAdZoneID)
    {
        RequestNormalInterstitialAd();
    }
}

**Comment by shawnkc** [comment]
Please let us know if this isn't resolved in our new repository at: https://github.com/AdColony/AdColony-Unity-Plugin.
