### ISSUE TITLE
Integration successful but ads are not showing

### ISSUE THREAD

**Issue by dhanrajsinh24** [AdColony/AdColony-Unity-SDK-3#33]
I have a successful integration of adcolony in my unity iOS game and I'm building with Unity 2017 v2.0 and xcode 8. when I try to show ad, nothing happens and video is not showing. What would be wrong?

**Comment by cmanibog-ac** [comment]
To look into this further, please let us know your AdColony app ID and share a full console log showing the app activity from when our SDK is initialized through an attempted video view. If a mediation layer is being used, which partner?

For streamlined communication with our support team and engineers, feel free to open this as a ticket at support@adcolony.com.

**Comment by dhanrajsinh24** [comment]
@cmanibog-ac Thanks for responding. 
Here's my app ID : app8e61954208b44cc082
Here's my xcode log related to adcolony : 
2017-12-08 13:52:10.767071+0530 spaceconnect[294:18969] AdColony [*Warning*] : Either configureWithAppID:options:completion: has not been called, or AdColony has not finished configuring yet. Ignoring API call
2017-12-08 13:52:10.767257+0530 spaceconnect[294:18969] AdColony [Info] : AdColony controller version: 1.0.8.13
EAAcwWawZAlMoBAIhHm90hSz4z9eWBKrd3CEMXU6Wz79VEJgQrZChCsHiGWSl6YlK6zrzzZBezToZB8XtLHtzSqt5ZADvQpki60x9nbtP6PWb370fTDKPgd9KQpyfy0eUXWhr4i8V2hQuiSn4eaIhFAdOgxJNQb6nDFZBgrreZAJEN7iZCkrFuSEu4GOa6XZApO8B8880ysBEfKcRXP9NthVv4ulZBHxbLQuSXBYhsyxG8ZCVEZCEm4dtZBcjU

**Comment by cmanibog-ac** [comment]
Your app and zone settings look fine in our dashboard. Does this error message appear if you allow a bit more time for our SDK to initialize before requesting a video to be shown? Could you also share a code snippet of your configure call?

**Comment by dhanrajsinh24** [comment]
@cmanibog-ac Yes, the problem was - configuration was not finished and the request for an ad was made. I already solved it a couple of days ago but Thanks anyway.

**Comment by arslaaaan** [comment]
Hey dhanrajsinh24,
I am facing same problem in my android game on unity, can you guide me how you solved this.

**Comment by RanjeetStiga** [comment]
> @cmanibog-ac Yes, the problem was - configuration was not finished and the request for an ad was made. I already solved it a couple of days ago but Thanks anyway.

How to solved it ? its problem on dashbaord or coding part

**Comment by ardakaplan** [comment]
I have same issue on android. Debug mode application shows test ads. But when i run release application, no adverts shown and "onRequestNotFilled" method triggred. What  must be changed ?

**Comment by RAZA1001** [comment]
I have same issue test ad working fine but live ads not showing

**Comment by Aihabam** [comment]
Same issue here

**Comment by imarindam** [comment]
Same Problem but with Android Banner integration.

**Comment by enwokoma** [comment]
Same problem with Android banner integration

**Comment by imarindam** [comment]
It should be fixed. I am seeing 0 impressions. Please fix it. My app is live at Playstore. Test ads were working fine.

**Comment by dipankar108** [comment]
I am seeing 0 impressions. Please fix it. My app is live at Playstore. Test ads were working fine.

**Comment by vaibhavpandeyvpz** [comment]
I believe your integrations are fine if you make sure you only request an ad once configured as mentioned by @dhanrajsinh24. The reason why test ads showing but live ads not, that might be because the app isn't eligible just yet for live ads. Just finish integrating and let your app generate impressions for a while (I mean days), they will start showing.

**Comment by mayank-srm** [comment]
It should be fixed. I am seeing 0 impressions. Please fix it. My app is live at Playstore. Test ads were working fine.

**Comment by MehdiAbyat** [comment]
Same problem with Android banner integration
