### ISSUE TITLE
During build Gradle shows warning

### ISSUE THREAD

**Issue by patinvedis** [AdColony/AdColony-Unity-SDK-3#36]
When I build my project (Unity 2.7.2) with Gradle The following warning is displayed and the build fails:
Warning:com.adcolony.unityplugin.UnityADCActivity: can't find referenced method 'UnityPlayer(android.content.ContextWrapper)' in program class com.unity3d.player.UnityPlayer
I am using the latest AdColony Unity sdk 3
Any idea?

**Comment by patinvedis** [comment]
I built again the project with Unity internal system and it worked flawlessly. I have no idea why it didn't work with gradle...

**Comment by JimmyDeemo** [comment]
@patinvedis @regy42 Did either of you solve this when using the Gradle option? I have the same problem, and need to utilise Gradle for building also. Can't see a way around this warning as it stops builds. Any help much appreciated.

**Comment by JimmyDeemo** [comment]
In case anyone else stumbles on this problem, I got in touch with Untity support to try and resolve this. I got around the problem by adding a ProGuard entry to not warn you about these classes;

```
-dontwarn com.unity3d.player.**
```

Unity advised that this was OK and postulated that the following might be happening;

> The method calls in the code are collected.
> In this case UnityADCActivity calls UnityPlayer(android.content.ContextWrapper).
> UnityPlayer(android.content.ContextWrapper) gets added to the stripping blacklist.
> The presence of UnityPlayer(android.content.ContextWrapper) is checked in the UnityPlayer class (it's not there).
> It ends up not stripping UnityPlayer(android.content.ContextWrapper) which doesn't exist, so the actual constructor UnityPlayer(android.content.Context) gets stripped.
> The program should crash at runtime.
> However the actual constructor is likely preserved because it's listed somewhere in the ProGuard configuration, so the program doesn't crash.
> The warning remains.

Hope that helps.
