### ISSUE TITLE
App crashes when ad closed on iOS

### ISSUE THREAD

**Issue by FazalEllahi** [AdColony/AdColony-Unity-SDK-3#37]
I have integrated the Adcolony latest plugin in my Unity App. When Build for iOS, after closing the ad, my app got crashed. this is the log from Xcode, I m running my app in Landscape

> MTLDebugRenderCommandEncoder setScissorRect:]:2163: failed assertion `(rect.x(0) + rect.width(1334))(1334) must be <= 750'

**Comment by cmanibog-ac** [comment]
To look in to this further, could you share the full console log showing the app activity from when our SDK is initialized through the crash? Please also confirm that this is our 3.2.1 Unity plugin and if a mediation layer is being used, which partner? Feel free to send this information to our Support team at support@adcolony.com for direct communication with our Support and Engineering teams.
