### ISSUE TITLE
AdColony.Ads.OnRewardGranted called with interstitial ads

### ISSUE THREAD

**Issue by Warface** [AdColony/AdColony-Unity-SDK-3#4]
I've added a reward ad which run fine and get the OnRewardGranted callback but now each time a normal interstital ad is fired, the OnRewardGranted callback is called too. Shouldn't that be another callback?

**Comment by cmanibog-ac** [comment]
For further troubleshooting, please open a ticket with our Support team by sending a message to support@adcolony.com. In the message, send a full console log showing the app activity from when our SDK is initialized through an interstitial video view and the OnRewardGranted callback being called.
