### ISSUE TITLE
Missing steps in Quick Start instructions

### ISSUE THREAD

**Issue by yurfdog** [AdColony/AdColony-Unity-SDK-3#41]
Here in the [AdColony-SDK-Integration-Quick-Start-Guide](https://github.com/AdColony/AdColony-Unity-SDK-3/wiki/AdColony-SDK-Integration-Quick-Start-Guide)
it says... 

> Then retrieve your app ID and your corresponding zone IDs from the AdColony website and make note of them for use in Step 4. 

But there is no Step 4 (or 3).  There are only 2 steps listed on the page.

**Comment by shawnkc** [comment]
This repository is no longer being maintained. We took your feedback into account during the generation of the new repository. Please see: https://github.com/AdColony/AdColony-Unity-Plugin.
