### ISSUE TITLE
Setting custom_id for rewarded apps

### ISSUE THREAD

**Issue by edencakir** [AdColony/AdColony-Unity-SDK-3#43]
Is there a way to set custom_id at runtime?

Android sdk supports this feature: https://github.com/AdColony/AdColony-Android-SDK-3/wiki/Showing-Rewarded-Interstitial-Ads#rewarded-app-options

**Comment by shawnkc** [comment]
The CUSTOM_ID field mentioned in the callback is populated from the AppOptions.UserId field. The UID field is an internal id. I will update the docs to clarify this.
