### ISSUE TITLE
ADCDependencies breaks the Play Service Resolver

### ISSUE THREAD

**Issue by JSC-Sparkling** [AdColony/AdColony-Unity-SDK-3#44]
ADCDependencies breaks the Play Service Resolver (PSR) when using a newer PSR than present in the package.  
The usage of a newer PSR isn't uncomming because other plugins in a project may require a newer version.  
  
The issues is how ADC's dependency version is written, `9.+`. This notation breaks newer PSR versions, causing incorrect resolutions to occur.
To resolve this issue I found that replacing `9.+` with `9.0+` is enough. This'll fix the resolution process for newer PSRs.  
  
P.S. Newer PSRs have a new XML format for Dependencies, it would be a nice sur-plus if ADC would use the newer format too.

**Comment by shawnkc** [comment]
This repository is no longer being maintained as we've transitioned to an open-source model for the plugin. Feel free to make a pull-request concerning your issue. 

See: https://github.com/AdColony/AdColony-Unity-Plugin.
