### ISSUE TITLE
The Compass SDK Integration Guide is not wrong

### ISSUE THREAD

**Issue by saehyun** [AdColony/AdColony-Unity-SDK-3#6]
Initialization code is as follows.

    // Must be first!
    // Configure AdColony for Ads
    AdColony.Configure(AppVersion, AdColonyAppId, null, AdColonyZone1, ...);

    // Configure AdColony for Publisher Services
    AdColonyPubServices.PubServices.Configure();

But, I couldn't use it.
I think the correct code is as follows.

    // Must be first!
    // Configure AdColony for Ads
    AdColony.Ads.Configure(AdColonyAppId, AppOptions, AdColonyZone1, ...);

    // Configure AdColony for Publisher Services
    AdColony.PubServices.Configure();

Please fix the guide.
THX.

**Comment by cmanibog-ac** [comment]
Thank you for this feedback. Our teams have looked into this and have updated our documentation.
