### ISSUE TITLE
conflict with google play services

### ISSUE THREAD

**Issue by khmaies5** [AdColony/AdColony-Unity-SDK-3#7]
when i import adcolony plug to a project containing play services plugin i get this errors

> Assets/AdColony/Editor/ADCDependencies.cs(10,23): error CS0433: The imported type `Google.JarResolver.PlayServicesSupport' is defined multiple times

> Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs(146,56): error CS0433: The imported type `Google.JarResolver.Dependency' is defined multiple times

**Comment by khmaies5** [comment]
to fix this problem you need to delete PlayServicesResolver folder and importe it again from Play services plugin (not adcolony plugin)

**Comment by cmanibog-ac** [comment]
Thank you for this feedback. I will pass this on to our Engineering team for review.

**Comment by colorgames** [comment]
@cmanibog-ac it is a shame that the problem still exists but I am glad the workaround @khmaies5 provided still works as well.

**Comment by htsoft** [comment]
I've tried to follow @khmaies5 comment but it still doesn't work for me. The Play Services package is 0.9.36.
