### ISSUE TITLE
ARMv7 build considered as FAT by Google Play Console

### ISSUE THREAD

**Issue by JoRouss** [AdColony/AdColony-Unity-SDK-3#9]
Hi, I always do ARMv7 build and x86 build seperatly to reduce file size. After importing AdColony, my ARMv7 build and my x86 build are both considered FAT when I upload them to Google Play.

In fact, they are not FAT, since I built a FAT build for testing, and it weights 10 Mb more than the ARMv7 and x86.

Can this be caused by AdColony? If yes, any way to fix this?

EDIT: Just removed AdColony and everything works as expected...

**Comment by cmanibog-ac** [comment]
I've reached out to our Engineering team for additional guidance on this. We'll follow up after they review these details or if we need more information.

**Comment by cmanibog-ac** [comment]
Could I have you try removing the Assets/Plugins/Android/AdColony/libs/x86 directory before building for ARMv7? And the opposite when they are building for x86 (removing the Assets/Plugins/Android/AdColony/libs/armeabi-v7a directory)?

Having both architectures present might be causing the build to think it needs to be a FAT build.

**Comment by JoRouss** [comment]
Currently, I removed AdColony from my project, because I had too many errors and conflicts with the current Google Play Services version.

When your SDK will be updated, I will give it another try and tell you the results.

**Comment by JoRouss** [comment]
I finally decided to give it another try.

Removing the unnecessary lib fixed it. They were both included in the build, even if unity was not set to FAT...

I hope you will fix this. I don't want to delete/reimport those libs everytime I make a build.

Thank you

**Comment by cmanibog-ac** [comment]
Glad to hear you were able to build this. Our Engineering team has filed a bug for this and should be fixed in a future update.
